### ISSUE TITLE
Define requirements

### ISSUE THREAD

**Issue by VaradiTamas** [VaradiTamas/sfa-documentation#3]
**Description**

According to the product description and component diagram define the main requirements of the project and split these into epic issues.

**Tasks**

- [x] Create a list of the main requirements (separately)
- [ ] Mark requirements for the next development phase (12 weeks)
- [ ] Documenting in wiki
- [ ] Split the main requirements into github epic issues
